name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: apt install libncurses5-dev libncursesw5-dev -y
    - uses: actions/checkout@v4
    - name: make
      run: make
